### ISSUE TITLE
${revision} is not resolved within dependencyManagement

### ISSUE THREAD

**Issue by oliverlockwood** [jcgay/unique-revision-maven-filtering#13]
@jcgay - this project looks great and is *almost* what we need.

We have a scenario with multimodule projects, e.g in the following simplified example (irrelevant XML objects skipped for brevity)

Root POM:
```xml
<project>

  <groupId>com.oliverlockwood</groupId>
  <artifactId>test</artifactId>
  <name>Test Project</name>
  <packaging>pom</packaging>
  <version>${revision}</version>

  <modules>
    <module>Commons</module>
    <module>Client</module>
    <module>Service</module>
  </modules>

  <properties>
    <revision>DEV</revision>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.oliverlockwood</groupId>
        <artifactId>test-commons</artifactId>
        <version>${revision}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

</project>
```

(we do it this way, because both `client` and `service` modules depend on the `commons` module).

At present the root project pom (as published in `.m2/repository/` and deployed to our Nexus) still contains `${revision}` in dependency management rather than a resolved version, which leads to all the problems documented in your blog post (https://jeanchristophegay.com/en/posts/maven-unique-version-multi-modules-build/) and the other blog post I found previously (https://axelfontaine.com/blog/maven-releases-steroids-2.html).

From a little experimentation I believe it would be trivial to extend the functionality of this useful Maven extension, so I intend to submit a PR with the changes.  This issue is raised to give advance notice and context.

**Comment by jcgay** [comment]
Sure if it serves your case I'll be glad to merge it 👍

I think it can also be solved by using `${project.version}` instead of `${revision}` in your `dependencyManagement` section ?

The flatten-maven-plugin have also gain a `resolveCiFriendliesOnly` since this extension, https://maven.apache.org/maven-ci-friendly.html (section `Install/Deploy`).

**Comment by oliverlockwood** [comment]
@jcgay - thank you for being so responsive and welcoming to my raised issue and PR submission!

We had previously been using `${project.version} in our POMs` but this left unresolved placeholders in our published POMs - hence the switch to a new approach using `${revision}` etc.

Your pointer to the `flatten-maven-plugin` usage was very helpful - after consideration, we have decided to go down that road, on the basis that that plugin has wider adoption than this extension and therefore is more likely to be a long-term solution as Maven itself evolves.  So although we won't end up using your extension, thank you for the opportunity to learn more about maven extensions 🙂

**Comment by jcgay** [comment]
Sure, glad it helps you :)

The `flatten-maven-plugin` is indeed the official way to go now!
